// source: network_packets.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var elevatu_objects_pb = require('./elevatu_objects_pb.js');
goog.object.extend(proto, elevatu_objects_pb);
goog.exportSymbol('proto.elevatu.ExerciseAddRequest', null, global);
goog.exportSymbol('proto.elevatu.ExerciseList', null, global);
goog.exportSymbol('proto.elevatu.UserList', null, global);
goog.exportSymbol('proto.elevatu.UserSession', null, global);
goog.exportSymbol('proto.elevatu.WorkoutLogAddRequest', null, global);
goog.exportSymbol('proto.elevatu.WorkoutLogList', null, global);
goog.exportSymbol('proto.elevatu.WorkoutPlanAddRequest', null, global);
goog.exportSymbol('proto.elevatu.WorkoutPlanList', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.elevatu.UserList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.elevatu.UserList.repeatedFields_, null);
};
goog.inherits(proto.elevatu.UserList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.elevatu.UserList.displayName = 'proto.elevatu.UserList';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.elevatu.WorkoutPlanList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.elevatu.WorkoutPlanList.repeatedFields_, null);
};
goog.inherits(proto.elevatu.WorkoutPlanList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.elevatu.WorkoutPlanList.displayName = 'proto.elevatu.WorkoutPlanList';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.elevatu.ExerciseList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.elevatu.ExerciseList.repeatedFields_, null);
};
goog.inherits(proto.elevatu.ExerciseList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.elevatu.ExerciseList.displayName = 'proto.elevatu.ExerciseList';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.elevatu.WorkoutLogList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.elevatu.WorkoutLogList.repeatedFields_, null);
};
goog.inherits(proto.elevatu.WorkoutLogList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.elevatu.WorkoutLogList.displayName = 'proto.elevatu.WorkoutLogList';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.elevatu.UserSession = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.elevatu.UserSession, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.elevatu.UserSession.displayName = 'proto.elevatu.UserSession';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.elevatu.ExerciseAddRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.elevatu.ExerciseAddRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.elevatu.ExerciseAddRequest.displayName = 'proto.elevatu.ExerciseAddRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.elevatu.WorkoutPlanAddRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.elevatu.WorkoutPlanAddRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.elevatu.WorkoutPlanAddRequest.displayName = 'proto.elevatu.WorkoutPlanAddRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.elevatu.WorkoutLogAddRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.elevatu.WorkoutLogAddRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.elevatu.WorkoutLogAddRequest.displayName = 'proto.elevatu.WorkoutLogAddRequest';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.elevatu.UserList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.elevatu.UserList.prototype.toObject = function(opt_includeInstance) {
  return proto.elevatu.UserList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.elevatu.UserList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.elevatu.UserList.toObject = function(includeInstance, msg) {
  var f, obj = {
    usersList: jspb.Message.toObjectList(msg.getUsersList(),
    elevatu_objects_pb.User.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.elevatu.UserList}
 */
proto.elevatu.UserList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.elevatu.UserList;
  return proto.elevatu.UserList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.elevatu.UserList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.elevatu.UserList}
 */
proto.elevatu.UserList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new elevatu_objects_pb.User;
      reader.readMessage(value,elevatu_objects_pb.User.deserializeBinaryFromReader);
      msg.addUsers(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.elevatu.UserList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.elevatu.UserList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.elevatu.UserList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.elevatu.UserList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUsersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      elevatu_objects_pb.User.serializeBinaryToWriter
    );
  }
};


/**
 * repeated User users = 1;
 * @return {!Array<!proto.elevatu.User>}
 */
proto.elevatu.UserList.prototype.getUsersList = function() {
  return /** @type{!Array<!proto.elevatu.User>} */ (
    jspb.Message.getRepeatedWrapperField(this, elevatu_objects_pb.User, 1));
};


/**
 * @param {!Array<!proto.elevatu.User>} value
 * @return {!proto.elevatu.UserList} returns this
*/
proto.elevatu.UserList.prototype.setUsersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.elevatu.User=} opt_value
 * @param {number=} opt_index
 * @return {!proto.elevatu.User}
 */
proto.elevatu.UserList.prototype.addUsers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.elevatu.User, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.elevatu.UserList} returns this
 */
proto.elevatu.UserList.prototype.clearUsersList = function() {
  return this.setUsersList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.elevatu.WorkoutPlanList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.elevatu.WorkoutPlanList.prototype.toObject = function(opt_includeInstance) {
  return proto.elevatu.WorkoutPlanList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.elevatu.WorkoutPlanList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.elevatu.WorkoutPlanList.toObject = function(includeInstance, msg) {
  var f, obj = {
    workoutplansList: jspb.Message.toObjectList(msg.getWorkoutplansList(),
    elevatu_objects_pb.WorkoutPlan.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.elevatu.WorkoutPlanList}
 */
proto.elevatu.WorkoutPlanList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.elevatu.WorkoutPlanList;
  return proto.elevatu.WorkoutPlanList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.elevatu.WorkoutPlanList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.elevatu.WorkoutPlanList}
 */
proto.elevatu.WorkoutPlanList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new elevatu_objects_pb.WorkoutPlan;
      reader.readMessage(value,elevatu_objects_pb.WorkoutPlan.deserializeBinaryFromReader);
      msg.addWorkoutplans(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.elevatu.WorkoutPlanList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.elevatu.WorkoutPlanList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.elevatu.WorkoutPlanList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.elevatu.WorkoutPlanList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWorkoutplansList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      elevatu_objects_pb.WorkoutPlan.serializeBinaryToWriter
    );
  }
};


/**
 * repeated WorkoutPlan workoutPlans = 1;
 * @return {!Array<!proto.elevatu.WorkoutPlan>}
 */
proto.elevatu.WorkoutPlanList.prototype.getWorkoutplansList = function() {
  return /** @type{!Array<!proto.elevatu.WorkoutPlan>} */ (
    jspb.Message.getRepeatedWrapperField(this, elevatu_objects_pb.WorkoutPlan, 1));
};


/**
 * @param {!Array<!proto.elevatu.WorkoutPlan>} value
 * @return {!proto.elevatu.WorkoutPlanList} returns this
*/
proto.elevatu.WorkoutPlanList.prototype.setWorkoutplansList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.elevatu.WorkoutPlan=} opt_value
 * @param {number=} opt_index
 * @return {!proto.elevatu.WorkoutPlan}
 */
proto.elevatu.WorkoutPlanList.prototype.addWorkoutplans = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.elevatu.WorkoutPlan, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.elevatu.WorkoutPlanList} returns this
 */
proto.elevatu.WorkoutPlanList.prototype.clearWorkoutplansList = function() {
  return this.setWorkoutplansList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.elevatu.ExerciseList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.elevatu.ExerciseList.prototype.toObject = function(opt_includeInstance) {
  return proto.elevatu.ExerciseList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.elevatu.ExerciseList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.elevatu.ExerciseList.toObject = function(includeInstance, msg) {
  var f, obj = {
    exercisesList: jspb.Message.toObjectList(msg.getExercisesList(),
    elevatu_objects_pb.Exercise.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.elevatu.ExerciseList}
 */
proto.elevatu.ExerciseList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.elevatu.ExerciseList;
  return proto.elevatu.ExerciseList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.elevatu.ExerciseList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.elevatu.ExerciseList}
 */
proto.elevatu.ExerciseList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new elevatu_objects_pb.Exercise;
      reader.readMessage(value,elevatu_objects_pb.Exercise.deserializeBinaryFromReader);
      msg.addExercises(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.elevatu.ExerciseList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.elevatu.ExerciseList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.elevatu.ExerciseList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.elevatu.ExerciseList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getExercisesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      elevatu_objects_pb.Exercise.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Exercise exercises = 1;
 * @return {!Array<!proto.elevatu.Exercise>}
 */
proto.elevatu.ExerciseList.prototype.getExercisesList = function() {
  return /** @type{!Array<!proto.elevatu.Exercise>} */ (
    jspb.Message.getRepeatedWrapperField(this, elevatu_objects_pb.Exercise, 1));
};


/**
 * @param {!Array<!proto.elevatu.Exercise>} value
 * @return {!proto.elevatu.ExerciseList} returns this
*/
proto.elevatu.ExerciseList.prototype.setExercisesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.elevatu.Exercise=} opt_value
 * @param {number=} opt_index
 * @return {!proto.elevatu.Exercise}
 */
proto.elevatu.ExerciseList.prototype.addExercises = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.elevatu.Exercise, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.elevatu.ExerciseList} returns this
 */
proto.elevatu.ExerciseList.prototype.clearExercisesList = function() {
  return this.setExercisesList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.elevatu.WorkoutLogList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.elevatu.WorkoutLogList.prototype.toObject = function(opt_includeInstance) {
  return proto.elevatu.WorkoutLogList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.elevatu.WorkoutLogList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.elevatu.WorkoutLogList.toObject = function(includeInstance, msg) {
  var f, obj = {
    workoutlogsList: jspb.Message.toObjectList(msg.getWorkoutlogsList(),
    elevatu_objects_pb.WorkoutLog.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.elevatu.WorkoutLogList}
 */
proto.elevatu.WorkoutLogList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.elevatu.WorkoutLogList;
  return proto.elevatu.WorkoutLogList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.elevatu.WorkoutLogList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.elevatu.WorkoutLogList}
 */
proto.elevatu.WorkoutLogList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new elevatu_objects_pb.WorkoutLog;
      reader.readMessage(value,elevatu_objects_pb.WorkoutLog.deserializeBinaryFromReader);
      msg.addWorkoutlogs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.elevatu.WorkoutLogList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.elevatu.WorkoutLogList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.elevatu.WorkoutLogList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.elevatu.WorkoutLogList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWorkoutlogsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      elevatu_objects_pb.WorkoutLog.serializeBinaryToWriter
    );
  }
};


/**
 * repeated WorkoutLog workoutLogs = 1;
 * @return {!Array<!proto.elevatu.WorkoutLog>}
 */
proto.elevatu.WorkoutLogList.prototype.getWorkoutlogsList = function() {
  return /** @type{!Array<!proto.elevatu.WorkoutLog>} */ (
    jspb.Message.getRepeatedWrapperField(this, elevatu_objects_pb.WorkoutLog, 1));
};


/**
 * @param {!Array<!proto.elevatu.WorkoutLog>} value
 * @return {!proto.elevatu.WorkoutLogList} returns this
*/
proto.elevatu.WorkoutLogList.prototype.setWorkoutlogsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.elevatu.WorkoutLog=} opt_value
 * @param {number=} opt_index
 * @return {!proto.elevatu.WorkoutLog}
 */
proto.elevatu.WorkoutLogList.prototype.addWorkoutlogs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.elevatu.WorkoutLog, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.elevatu.WorkoutLogList} returns this
 */
proto.elevatu.WorkoutLogList.prototype.clearWorkoutlogsList = function() {
  return this.setWorkoutlogsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.elevatu.UserSession.prototype.toObject = function(opt_includeInstance) {
  return proto.elevatu.UserSession.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.elevatu.UserSession} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.elevatu.UserSession.toObject = function(includeInstance, msg) {
  var f, obj = {
    username: jspb.Message.getFieldWithDefault(msg, 1, ""),
    secret: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.elevatu.UserSession}
 */
proto.elevatu.UserSession.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.elevatu.UserSession;
  return proto.elevatu.UserSession.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.elevatu.UserSession} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.elevatu.UserSession}
 */
proto.elevatu.UserSession.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUsername(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSecret(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.elevatu.UserSession.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.elevatu.UserSession.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.elevatu.UserSession} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.elevatu.UserSession.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUsername();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSecret();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string username = 1;
 * @return {string}
 */
proto.elevatu.UserSession.prototype.getUsername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.elevatu.UserSession} returns this
 */
proto.elevatu.UserSession.prototype.setUsername = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string secret = 2;
 * @return {string}
 */
proto.elevatu.UserSession.prototype.getSecret = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.elevatu.UserSession} returns this
 */
proto.elevatu.UserSession.prototype.setSecret = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.elevatu.ExerciseAddRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.elevatu.ExerciseAddRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.elevatu.ExerciseAddRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.elevatu.ExerciseAddRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    usersession: (f = msg.getUsersession()) && proto.elevatu.UserSession.toObject(includeInstance, f),
    exercise: (f = msg.getExercise()) && elevatu_objects_pb.Exercise.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.elevatu.ExerciseAddRequest}
 */
proto.elevatu.ExerciseAddRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.elevatu.ExerciseAddRequest;
  return proto.elevatu.ExerciseAddRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.elevatu.ExerciseAddRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.elevatu.ExerciseAddRequest}
 */
proto.elevatu.ExerciseAddRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.elevatu.UserSession;
      reader.readMessage(value,proto.elevatu.UserSession.deserializeBinaryFromReader);
      msg.setUsersession(value);
      break;
    case 2:
      var value = new elevatu_objects_pb.Exercise;
      reader.readMessage(value,elevatu_objects_pb.Exercise.deserializeBinaryFromReader);
      msg.setExercise(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.elevatu.ExerciseAddRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.elevatu.ExerciseAddRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.elevatu.ExerciseAddRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.elevatu.ExerciseAddRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUsersession();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.elevatu.UserSession.serializeBinaryToWriter
    );
  }
  f = message.getExercise();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      elevatu_objects_pb.Exercise.serializeBinaryToWriter
    );
  }
};


/**
 * optional UserSession userSession = 1;
 * @return {?proto.elevatu.UserSession}
 */
proto.elevatu.ExerciseAddRequest.prototype.getUsersession = function() {
  return /** @type{?proto.elevatu.UserSession} */ (
    jspb.Message.getWrapperField(this, proto.elevatu.UserSession, 1));
};


/**
 * @param {?proto.elevatu.UserSession|undefined} value
 * @return {!proto.elevatu.ExerciseAddRequest} returns this
*/
proto.elevatu.ExerciseAddRequest.prototype.setUsersession = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.elevatu.ExerciseAddRequest} returns this
 */
proto.elevatu.ExerciseAddRequest.prototype.clearUsersession = function() {
  return this.setUsersession(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.elevatu.ExerciseAddRequest.prototype.hasUsersession = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Exercise exercise = 2;
 * @return {?proto.elevatu.Exercise}
 */
proto.elevatu.ExerciseAddRequest.prototype.getExercise = function() {
  return /** @type{?proto.elevatu.Exercise} */ (
    jspb.Message.getWrapperField(this, elevatu_objects_pb.Exercise, 2));
};


/**
 * @param {?proto.elevatu.Exercise|undefined} value
 * @return {!proto.elevatu.ExerciseAddRequest} returns this
*/
proto.elevatu.ExerciseAddRequest.prototype.setExercise = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.elevatu.ExerciseAddRequest} returns this
 */
proto.elevatu.ExerciseAddRequest.prototype.clearExercise = function() {
  return this.setExercise(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.elevatu.ExerciseAddRequest.prototype.hasExercise = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.elevatu.WorkoutPlanAddRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.elevatu.WorkoutPlanAddRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.elevatu.WorkoutPlanAddRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.elevatu.WorkoutPlanAddRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    usersession: (f = msg.getUsersession()) && proto.elevatu.UserSession.toObject(includeInstance, f),
    workoutplan: (f = msg.getWorkoutplan()) && elevatu_objects_pb.WorkoutPlan.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.elevatu.WorkoutPlanAddRequest}
 */
proto.elevatu.WorkoutPlanAddRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.elevatu.WorkoutPlanAddRequest;
  return proto.elevatu.WorkoutPlanAddRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.elevatu.WorkoutPlanAddRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.elevatu.WorkoutPlanAddRequest}
 */
proto.elevatu.WorkoutPlanAddRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.elevatu.UserSession;
      reader.readMessage(value,proto.elevatu.UserSession.deserializeBinaryFromReader);
      msg.setUsersession(value);
      break;
    case 2:
      var value = new elevatu_objects_pb.WorkoutPlan;
      reader.readMessage(value,elevatu_objects_pb.WorkoutPlan.deserializeBinaryFromReader);
      msg.setWorkoutplan(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.elevatu.WorkoutPlanAddRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.elevatu.WorkoutPlanAddRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.elevatu.WorkoutPlanAddRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.elevatu.WorkoutPlanAddRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUsersession();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.elevatu.UserSession.serializeBinaryToWriter
    );
  }
  f = message.getWorkoutplan();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      elevatu_objects_pb.WorkoutPlan.serializeBinaryToWriter
    );
  }
};


/**
 * optional UserSession userSession = 1;
 * @return {?proto.elevatu.UserSession}
 */
proto.elevatu.WorkoutPlanAddRequest.prototype.getUsersession = function() {
  return /** @type{?proto.elevatu.UserSession} */ (
    jspb.Message.getWrapperField(this, proto.elevatu.UserSession, 1));
};


/**
 * @param {?proto.elevatu.UserSession|undefined} value
 * @return {!proto.elevatu.WorkoutPlanAddRequest} returns this
*/
proto.elevatu.WorkoutPlanAddRequest.prototype.setUsersession = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.elevatu.WorkoutPlanAddRequest} returns this
 */
proto.elevatu.WorkoutPlanAddRequest.prototype.clearUsersession = function() {
  return this.setUsersession(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.elevatu.WorkoutPlanAddRequest.prototype.hasUsersession = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional WorkoutPlan workoutPlan = 2;
 * @return {?proto.elevatu.WorkoutPlan}
 */
proto.elevatu.WorkoutPlanAddRequest.prototype.getWorkoutplan = function() {
  return /** @type{?proto.elevatu.WorkoutPlan} */ (
    jspb.Message.getWrapperField(this, elevatu_objects_pb.WorkoutPlan, 2));
};


/**
 * @param {?proto.elevatu.WorkoutPlan|undefined} value
 * @return {!proto.elevatu.WorkoutPlanAddRequest} returns this
*/
proto.elevatu.WorkoutPlanAddRequest.prototype.setWorkoutplan = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.elevatu.WorkoutPlanAddRequest} returns this
 */
proto.elevatu.WorkoutPlanAddRequest.prototype.clearWorkoutplan = function() {
  return this.setWorkoutplan(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.elevatu.WorkoutPlanAddRequest.prototype.hasWorkoutplan = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.elevatu.WorkoutLogAddRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.elevatu.WorkoutLogAddRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.elevatu.WorkoutLogAddRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.elevatu.WorkoutLogAddRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    usersession: (f = msg.getUsersession()) && proto.elevatu.UserSession.toObject(includeInstance, f),
    workoutlog: (f = msg.getWorkoutlog()) && elevatu_objects_pb.WorkoutLog.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.elevatu.WorkoutLogAddRequest}
 */
proto.elevatu.WorkoutLogAddRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.elevatu.WorkoutLogAddRequest;
  return proto.elevatu.WorkoutLogAddRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.elevatu.WorkoutLogAddRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.elevatu.WorkoutLogAddRequest}
 */
proto.elevatu.WorkoutLogAddRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.elevatu.UserSession;
      reader.readMessage(value,proto.elevatu.UserSession.deserializeBinaryFromReader);
      msg.setUsersession(value);
      break;
    case 2:
      var value = new elevatu_objects_pb.WorkoutLog;
      reader.readMessage(value,elevatu_objects_pb.WorkoutLog.deserializeBinaryFromReader);
      msg.setWorkoutlog(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.elevatu.WorkoutLogAddRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.elevatu.WorkoutLogAddRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.elevatu.WorkoutLogAddRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.elevatu.WorkoutLogAddRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUsersession();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.elevatu.UserSession.serializeBinaryToWriter
    );
  }
  f = message.getWorkoutlog();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      elevatu_objects_pb.WorkoutLog.serializeBinaryToWriter
    );
  }
};


/**
 * optional UserSession userSession = 1;
 * @return {?proto.elevatu.UserSession}
 */
proto.elevatu.WorkoutLogAddRequest.prototype.getUsersession = function() {
  return /** @type{?proto.elevatu.UserSession} */ (
    jspb.Message.getWrapperField(this, proto.elevatu.UserSession, 1));
};


/**
 * @param {?proto.elevatu.UserSession|undefined} value
 * @return {!proto.elevatu.WorkoutLogAddRequest} returns this
*/
proto.elevatu.WorkoutLogAddRequest.prototype.setUsersession = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.elevatu.WorkoutLogAddRequest} returns this
 */
proto.elevatu.WorkoutLogAddRequest.prototype.clearUsersession = function() {
  return this.setUsersession(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.elevatu.WorkoutLogAddRequest.prototype.hasUsersession = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional WorkoutLog workoutLog = 2;
 * @return {?proto.elevatu.WorkoutLog}
 */
proto.elevatu.WorkoutLogAddRequest.prototype.getWorkoutlog = function() {
  return /** @type{?proto.elevatu.WorkoutLog} */ (
    jspb.Message.getWrapperField(this, elevatu_objects_pb.WorkoutLog, 2));
};


/**
 * @param {?proto.elevatu.WorkoutLog|undefined} value
 * @return {!proto.elevatu.WorkoutLogAddRequest} returns this
*/
proto.elevatu.WorkoutLogAddRequest.prototype.setWorkoutlog = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.elevatu.WorkoutLogAddRequest} returns this
 */
proto.elevatu.WorkoutLogAddRequest.prototype.clearWorkoutlog = function() {
  return this.setWorkoutlog(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.elevatu.WorkoutLogAddRequest.prototype.hasWorkoutlog = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.elevatu);
